# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "SwiftProjects.xcworkspace", scheme: "SwiftProjects")
    upload_to_testflight
  end
end

desc "打包到pgy"
lane :SwiftProjects do |options|
sigh(adhoc:true)  #如果要使用ad-hoc打包, 则需打开此项配置
gym(
  clean:true, #打包前clean项目
  export_method: "ad-hoc", #导出方式 # app-store, ad-hoc, package, enterprise, development, developer-id  
  scheme:"SwiftProjects", #scheme
  configuration: "Release",#环境
  output_directory:"./app",#ipa的存放目录
  output_name:"SwiftProjects",#get_build_number()#输出ipa的文件名为当前的build号
  )
  #使用自动证书管理
  enable_automatic_code_signing(path: "SwiftProjects.xcodeproj")
#蒲公英的配置 替换为自己的api_key和user_key
pgyer(api_key: "ebc82c852e88f461290c59b80eb80877", user_key: "8de9342d258b5779fbf4c4359df2473f",update_description: options[:desc])
end
